name: ariadne
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - pip
  - mafft
  - iqtree
  - numpy>=1.24
  - openpyxl>=3.1
  - pyhmmer>=0.12.0
  - pyrodigal>=3.7.0
  - scikit-learn>=1.4
  - pip:
      - -e .
